### ISSUE TITLE
Not working out of box

### ISSUE THREAD

**Issue by dudil** [microsoftgraph/dotnetcore-console-sample#2]
Hi,

Following the steps in the readme are resulted in an error response from the server 
(System.AggregateException):

"One or more errors occurred. (Code: Authorization_IdentityNotFound\nMessage: The identity of the calling application could not be established.\n\nInner error\n)"

I've used Visual Studio for Mac 2017 7.6.9 (build 22) with all packages updated.
.net core: 2.1.2
SDK Version: 2.1.302

I believe that during setting the app, might be more fields need to set up.
If that's true It will be good to include that in the Read Me.

**Comment by darrelmiller** [comment]
Thanks for letting us know.  We will investigate /cc @jthake-msft @jasonjoh

**Comment by jasonjoh** [comment]
Adding @BrianTJackett to comment. He's driving this project and I believe it's a work in progress, so he may have updates to the README to share :)

**Comment by dudil** [comment]
Thank you for your fast response here guys!
If you need any help more info from my side please let me know.

@darrelmiller - Basically I'm looking for a tutorial that will allow me to use .net core as serverless solution host on Lambda etc. for interacting with static web pages. (using Hugo etc.)

it seems to me that using ASP .net is an overkill to such simple pages where all you need is just to have an input form and then just do something on the backend as a response (like inviting new users etc.)

I hope to leverage this example for that - but are you familiar with something else that will better fit that requirement?

**Comment by BrianTJackett** [comment]
@dudil Yes this repo is a work in progress and we don't have the full set of instructions for walking through creation of Azure AD app, granting permissions, etc.  Sorry for not listing that in the README yet.  The goal is to make this repo similar to the ASP.Net Getting Started sample on the Microsoft Graph documentation site but instead using .Net Core.

As to your question about interacting with static web pages, I'm not familiar with Hugo.  What are the actions you are trying to accomplish against the static site?  Do you need UI interaction, link scraping, simple "hit a URL", or something else?

**Comment by dudil** [comment]
Hi @BrianTJackett  - That’s great, will be happy to assist once I’ll be actually be able to run that that.
[Hugo](
https://github.com/gohugoio/hugo) is static site generator, means rendering the whole page before deployment.
Pretty much like it for speed, simplicity and security.

I’m looking just to read some parameters from the website, send them to the API and just launch a simple backend process. more specific, to use the AAD API to have an add / remove users portal that could be share with key account holders with a better, simpler flow as there is today in the admin.
(Like to have a custom approval flow etc.) 
This is just a simple example why you won’t need a full blown ASP website as the website is only kind of form submission method.

To be honest, if I could utilize MS Forms to call a custom API that will even much cooler achievement :)

**Comment by BrianTJackett** [comment]
@dudil Working on the updates to README this week.  No promises but targeting end of this week.  If you'd be willing to test that would be a huge help, appreciate it in advance.

 In terms of a custom form entry calling into an API I recent built a prototype of MS Forms submission triggering an Azure Logic App that then made an HTTP Post to an Azure Automation runbook using inputs supplied from the form submission.  Let me know if you'd like a walkthrough or screenshots of the process.  Can take that offline.

**Comment by BrianTJackett** [comment]
Slight delay on updates as @darrelmiller provided an update to auth flow and also the preview of new Azure AD app registration portal is available.  Updating `dev` branch with these updates and making progress as time permits.

**Comment by dudil** [comment]
@BrianTJackett - thank you for the update.
Indeed worth waiting for that.

As per the Utilizing of the MS Forms. Will be happy to check it with you later on! Great!

**Comment by BrianTJackett** [comment]
@dudil I've made first pass at updating README to include the instructions needed for completing project from scratch.  My team and I will be going through it again this week to verify.  In the meantime would you be able to give it a try?  Let us know about any issues you run into or instructions that aren't clear.

**Comment by BrianTJackett** [comment]
@dudil we've added a few more updates and are getting ready to merge dev into master.  Please let us know if you've had a chance to test with the latest instructions.

**Comment by dudil** [comment]
Hi @BrianTJackett - no I didn't have the chance.
Will do it now and update before your merge :)

**Comment by Wayne-Mather** [comment]
@BrianTJackett  - I too cannot get this to work modifying your instructions to suite my code base.

Happy to have this as a separate issue if it is different from @dudil 

I get the following exception:

`
Current authenticated context is not valid for this request. This occurs when a request is made to an endpoint that requires user sign-in. For example, /me requires a signed-in user.  Acquire a token on behalf of a user to make requests to these endpoints.  Use the OAuth 2.0 authorization code flow for mobile and native apps and the OAuth 2.0 implicit flow for single-page web apps.`

I have been developing in .NET since the DNX days so I found the instructions easy to implement however, confused over why I get the authentication error. 

I have included my code below but of course have removed my variable data for security reasons:

```
static void Main(string[] args)
{
	var clientId = "-----";
	var tenantId = "-----;
	var clientSecret = "----";
	var redirectUri = "https://localhost:8080";

	var authority = $"https://login.microsoftonline.com/{tenantId}/v2.0";
	List<string> scopes = new List<string>();
	scopes.Add("https://graph.microsoft.com/.default");

	var cca = new ConfidentialClientApplication(clientId, authority, redirectUri, new ClientCredential(clientSecret), null, null);
	IAuthenticationProvider authenticationProvider  = new MsalAuthenticationProvider(cca, scopes.ToArray());
	var graphClient  = new GraphServiceClient(authenticationProvider);
	var httpClient = new HttpClient(new AuthHandler(authenticationProvider, new HttpClientHandler()));

	var inbox = graphClient.Me.MailFolders.Inbox.Request().GetAsync().Result;
	var messageCount = inbox.Messages.Count;
	for (int i = 0; i < messageCount; i += 1)
	{
		var msg = inbox.Messages[i];
		Console.WriteLine($"Found message {msg.Subject} from {msg.From.EmailAddress}");
	}

}
```

**Comment by BrianTJackett** [comment]
@Wayne-Mather This sample uses the client credential (aka app-only) authentication flow which means that there is no user context associated with the access token.  This is typically used for daemon services or server to server type calls.  As such you will not be able to call the "/me" endpoint within Microsoft Graph.  Can you try calling the endpoint in the sample for "/Users" to see if that returns a value as expected.

Please see [authentication-and-authorization-scenarios](https://developer.microsoft.com/en-us/graph/blogs/30daysmsgraph-day-12-authentication-and-authorization-scenarios/) for more details on authentication flows.

**Comment by BrianTJackett** [comment]
@dudil Which part of the code instructions doesn't match the repo?

Thank you for your suggestions.  We implemented a number of them along with feedback from other offline reviewers.  We have another update coming soon to allow for multiple versions of the project to exist in subfolders which will match product / service specific blog posts coming out soon.

A few responses on your items.
- We chose to use VSCode as it is cross-platform.
- Agreed MSA didn't make sense to call out here.
- "Blade" is the terminology that the Azure portal team refers to the UI where portions of the screen extend to the right as you navigate deeper into the hierarchy of resources or settings.
- Helper classes should be implemented now in master branch.
- Configuration should be stored in the appsettings.json file, not aware of a way to store in environment variables.  If you have a suggestion please submit PR.

Closing issue for now as items have been addressed.  If you find additional items please open a new issue and we'll be happy to look into.  Thanks for your assistance in testing.
