### ISSUE TITLE
error while running example from dotnetcore-console-sample base-console-app

### ISSUE THREAD

**Issue by borys86** [microsoftgraph/dotnetcore-console-sample#44]
I have the following error, 
Inner Exception:
ServiceException: Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.

I checked that following permissions are granted:
![image](https://user-images.githubusercontent.com/1665527/49859249-5df6b980-fdf7-11e8-81aa-fe8b41e00cdd.png)
any ideas on where to dig further? 

Microsoft.Graph version used 1.12.0

**Comment by BrianTJackett** [comment]
If you are working on the base-console-app example you'll need to assign Application permissions.  From the screenshot you provided it looks like you have Delegated permissions assigned.  See the README that links to the below image for choosing Application permissions instead.  Let us know if any issues after updating and re-testing.

https://github.com/microsoftgraph/dotnetcore-console-sample/blob/master/base-console-app/Images/aad-create-app-06.png

**Comment by BrianTJackett** [comment]
@borys86 can you please provide an update.  If don't hear back in a few days I'll be closing this issue but can re-open if needed.  Thanks.

**Comment by borys86** [comment]
hi Brian
you were right. It was my fault to report this issue.

**Comment by BrianTJackett** [comment]
@borys86 not a problem.  Thanks for bringing it up.  Let us know if any other issues you encounter.
