### ISSUE TITLE
Update to GA version of MSAL v4

### ISSUE THREAD

**Issue by BrianTJackett** [microsoftgraph/dotnetcore-console-sample#48]

**Comment by gavinbarron** [comment]
Hey Brian, do we want to use the graph specific SDK that wraps this?

**Comment by BrianTJackett** [comment]
Are you referring to the [Microsoft.Graph.Auth](https://www.nuget.org/packages/Microsoft.Graph.Auth/0.1.0-preview.2) NuGet package?  I think that is what Darrel was demo'ing on previous Microsoft Graph community call correct?  If so it is currently in preview.  I'd prefer to stick with GA of MSAL v3 (3.0.8 at the moment) first.  I already have a first start at updating in my own fork of this repo, [feature-msalv3 branch](https://github.com/BrianTJackett/dotnetcore-console-sample/tree/feature-MSALv3).  Not yet finished but take a look.

**Comment by BrianTJackett** [comment]
Updating code and issue to reflect MSAL .Net v4 as that was released this month.

**Comment by BrianTJackett** [comment]
Scheduling blog post for publish 6/11/2019.  Merged #50 to implement these features.
