### ISSUE TITLE
Update Day 28 Webhooks sample to .Net Core 3.1

### ISSUE THREAD

**Issue by BrianTJackett** [microsoftgraph/dotnetcore-console-sample#55]
The webhooks sample is a .Net Core Web API which differs from the console applications used for most other samples.  Looking for assistance in updating due to lack of availability to work through the necessary changes.

**Comment by gavinbarron** [comment]
I'll take a look at this tonight

**Comment by BrianTJackett** [comment]
Closing issue, see comments in #58 regarding potentially moving webhook sample to another repo.
