### ISSUE TITLE
All Planner plans 

### ISSUE THREAD

**Issue by parthrawal** [microsoftgraph/dotnetcore-console-sample#78]
what kind of authentication i should be passing to access all planner plans and their tasks. aparently i can not access plans where i am not part of.... which is causing an issue with my application. 

any thoughts on authentication strategy where i can access all plans through graph api.

**Comment by BrianTJackett** [comment]
Planner APIs for Microsoft Graph currently only support delegated authentication (i.e. currently logged in user).  If you want to list all plans within a tenant I believe you would need to iterate over all groups and then each plan within a group.  This would use Group.Read.All or Group.ReadWrite.All, but I haven't verified.

[List groups](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http)
[List plans of a group](https://docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-1.0&tabs=http)

**Comment by BrianTJackett** [comment]
More info on delegated vs. application permissions
[https://docs.microsoft.com/en-us/graph/auth/auth-concepts?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#delegated-and-application-permissions](https://docs.microsoft.com/en-us/graph/auth/auth-concepts?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#delegated-and-application-permissions)
